# Generated by Django 4.2 on 2024-03-02 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="tecnology",
            new_name="technology",
        ),
    ]
